package com.example.myanalyticssdk.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single analytics event stored in the local Room database.
 * Marked as 'internal' to encapsulate data structure within the SDK.
 */
@Entity(tableName = "analytics_events")
internal data class AnalyticsEvent(
    /**
     * Unique ID for the event, auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    /**
     * The name of the event (e.g., "Button_Clicked", "Screen_View").
     */
    val eventName: String,

    /**
     * The event properties stored as a JSON string.
     * This allows storing flexible, unstructured data (Map<String, Any>) in a SQL table.
     */
    val jsonPayload: String,

    /**
     * The time when the event was created (in milliseconds).
     * Defaults to the current system time.
     */
    val timestamp: Long = System.currentTimeMillis()
)